### ISSUE TITLE
Hello, camenlx!

### ISSUE THREAD

**Issue by username1565** [camenlx/hello-world#1]
Hello, @camenlx!
I see you have opened issues for this repositary.
But for some repositaries, you have no enabled "Issues"
So I write here, just to contact with you.
You can enable issues for each your repositary, in the settings of this. "Settings"->checkbox "Issues".

*Best regards*

**Comment by camenlx** [comment]
Hi, thanks for question. I will open Lucky issues.
Forks by miners do happen and are common. Nodes will follow eventually, is not the longest blockchain but one with the highest in work/difficulty.
This code repo is a copy for open-source sake from abandoned project original devs. 
I do not have spork keys or exchanges contact access.
To make sw changes exchanges would have to agree to accept proposed enhancements.

You can choose your node's fork, backup wallet.dat, add connect to nodes you trust, clean all block data and resync.

try to put in your conf file:
invalidateblock=0000001b29d5cc155aa5c31ab90433dce8fcc76cdf669ca93c63d97c9858f223
reconsiderblock=00000008556d5087e14b5179e0c4b4c885511247e84912c0988b8cf4dd7b0c9c
assumevalid=0000001d068f2738b3c0fa369e1c7abd9bd3fc0fca64721d9ebb83586ce064c9

and re-open node or with re-index
I will try reindex my ones also.

**Comment by username1565** [comment]
@camenlx, thanks for your answer, this seems, like OK, now.

**Comment by camenlx** [comment]
Yes sw function exists for it https://github.com/camenlx/luckycore/blob/master/src/main.cpp#L3332
ActivateBestChain, is only called at node init, spork call ReprocessBlocks by dev-secret-owner, or rpc/cli invalidateblock also looks for best blockchain.

My guess is there are many phantom nodes that cause real nodes to become surrounded and alone in pools of phantom neighborhoods. All real nodes (miner-nodes, masternodes, exchanges and wallet-nodes) that are unLucky and not connected to good real nodes may get blocks from loser forks and remain stuck until human operator notices and act like you did. 

In zeroonecoin we have implemented auto-healing in release 0.12.3.7 
https://github.com/zocteam/zeroonecoin/releases/tag/v0.12.3.7

**Comment by username1565** [comment]
Anyway, you can close this issue.
